language: python
python:
	-"2.7"
	-"3.6"
env:
- CODECOV_TOKEN='68d8495b-db7a-449e-8f4d-3197076e8427'
after_success:
  bash <(curl -s https://codecov.io/bash

addons:
ssh_known_hosts: moon.scs.ryerson.ca

install:
- pip install -r requirements.txt

script:
python -m pytest

